import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className=" flex justify-between px-10 pb-10 pt-5 bg-teal-400 h-16">
          <Link className=" text-xl text-pink-950" href="/">
            Home
          </Link>
          <Link className=" text-xl text-pink-950" href="/posts">
            Posts
          </Link>
          <Link className=" text-xl text-pink-950" href="/abdullah">
            Abdullah
          </Link>
        </nav>

        {children}
      </body>
    </html>
  );
}
